# Generated by Django 5.2.4 on 2025-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='estimated_time',
            field=models.DurationField(blank=True, help_text='Estimated preparation time', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step-by-step instructions', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or tips', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.PositiveIntegerField(blank=True, help_text='Number of servings', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='untitled recepie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
